apiVersion: core.cpc.platform.confluent.io/v1beta1
kind: KafkaRestProxyClusterClass
metadata:
  name: kafkarestproxy-standard
  namespace: cpc-system
  annotations:
    cpc.platform.confluent.io/description: "This TILE represents pre-set configuration to deploy CP KafkaRestProxy Cluster."
spec:
  provisioner:
    type: cfk
    cfk:
      replicas: 3
