apiVersion: v1
kind: Pod
metadata:
  name: network-test
spec:
  containers:
    - name: alpine
      image: alpine
      securityContext:
        privileged: true
      args:
        - sleep
        - "999999"