apiVersion: v1
kind: Service
metadata:
  labels:
    dns.operator.openshift.io/owning-dns: default
  name: openshift-dns-lb
  namespace: openshift-dns
spec:
  ports:
    - name: dns
      port: 53
      protocol: UDP
      targetPort: dns
  selector:
    dns.operator.openshift.io/daemonset-dns: default
  type: LoadBalancer
