apiVersion: cluster.cpc.platform.confluent.io/v1beta1
kind: ZookeeperCluster
metadata:
  name: zookeeper-prod
  namespace: org-confluent
  annotations:
    cpc.platform.confluent.io/description: "This TILE represents Zookeeper cluster deployment in mothership Kubernetes cluster."
spec:
  blueprintRef:
    name: standard
    namespace: cpc-system
  k8sClusterRef:
    name: mothership
    namespace: cpc-system
