apiVersion: platform.confluent.io/v1beta1
kind: Zookeeper
metadata:
  name: zookeeper0
  namespace: central
  annotations:
    platform.confluent.io/zookeeper-myid-offset: "0"
spec:
  externalAccess:
    type: loadBalancer
    loadBalancer:
      domain: platformops.dev.gcp.devel.cpdev.cloud
      advertisedURL:
        enabled: true
        prefix: zk-central
      prefix: zk-central
  authentication:
    jaasConfig:
      secretRef: credential
    type: digest
  peers:
    - server.0=0.0.0.0:2888:3888
    - server.10=zk-east0.platformops.dev.gcp.devel.cpdev.cloud:2888:3888
    - server.11=zk-east1.platformops.dev.gcp.devel.cpdev.cloud:2888:3888
    - server.20=zk-west0.platformops.dev.gcp.devel.cpdev.cloud:2888:3888
    - server.21=zk-west1.platformops.dev.gcp.devel.cpdev.cloud:2888:3888
  dataVolumeCapacity: 10Gi
  image:
    application: confluentinc/cp-zookeeper:7.4.1
    init: confluentinc/confluent-init-container:2.6.1
  logVolumeCapacity: 10Gi
  replicas: 1
  tls:
    autoGeneratedCerts: true
