apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      name: grafana
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:latest
        env:
        - name: GF_PATHS_CONFIG
          value: "/opt/grafana/grafana.ini"
        ports:
        - name: grafana
          containerPort: 3000
        resources:
          limits:
            memory: "1Gi"
            cpu: "1000m"
          requests: 
            memory: 500M
            cpu: "500m"
        volumeMounts:
          - mountPath: /var/lib/grafana
            name: grafana-tmp-storage
        # Uncomment this for grafana.ini file
          - mountPath: /opt/grafana
            name: ge-config
          - mountPath: /etc/grafana/provisioning/datasources
            name: grafana-datasources
            readOnly: false
      volumes:
        - name: grafana-tmp-storage
          emptyDir: {}
        # - name: grafana-persistent-storage
        #   persistentVolumeClaim:
        #     claimName: graf-data-dir-pvc
        - name: ge-config
          configMap:
            name: ge-config 
        - name: grafana-datasources
          configMap:
              defaultMode: 420
              name: grafana-datasources
      
            