apiVersion: core.cpc.platform.confluent.io/v1beta1
kind: KafkaClusterClass
metadata:
  name: kafka-standard
  namespace: cpc-system
  annotations:
    cpc.platform.confluent.io/description: "This TILE represents pre-set configuration to deploy CP Kafka Cluster."
spec:
  provisioner:
    type: cfk
    cfk:
      replicas: 3
      # +optional
      image:
        application:
          registry: docker.io
          repository: confluentinc/cp-server
          tag: 7.2.0
        init:
          registry: docker.io
          repository: confluentinc/confluent-init-container
          tag: 2.4.0
      volume:
        data:
          capacity: 10Gi
