apiVersion: core.cpc.platform.confluent.io/v1beta1
kind: SchemaRegistryClusterClass
metadata:
  name: schemaregistry-standard
  namespace: cpc-system
  annotations:
    cpc.platform.confluent.io/description: "This TILE represents pre-set configuration to deploy CP SchemaRegistry Cluster."
spec:
   provisioner:
    type: cfk
    cfk:
      replicas: 3
      # +optional
      image:
        application:
          registry: docker.io
          repository: confluentinc/cp-schema-registry
          tag: 7.0.0
        init:
          registry: docker.io
          repository: confluentinc/confluent-init-container
          tag: 2.2.1
      internalTopicReplicationFactor: 3
