# rolebinding `internal-controlcenter-0` gives user `c3` the role `SystemAdmin`
apiVersion: platform.confluent.io/v1beta1
kind: ConfluentRolebinding
metadata:
  name: internal-controlcenter-0
spec:
  principal:
    name: c3
    type: user
  role: SystemAdmin