---
apiVersion: platform.confluent.io/v1beta1
kind: Zookeeper
metadata:
  name: zookeeper
  namespace: origin
spec:
  replicas: 3
  image:
    application: confluentinc/cp-zookeeper:7.0.0
    init: confluentinc/confluent-init-container:2.2.0
    pullSecretRef:
      - confluent-registry
  dataVolumeCapacity: 10Gi
  logVolumeCapacity: 10Gi
  authentication:
    type: mtls
  tls:
    secretRef: origin-tls-group1
---
apiVersion: platform.confluent.io/v1beta1
kind: Kafka
metadata:
  name: kafka
  namespace: origin
spec:
  replicas: 3
  image:
    application: confluentinc/cp-server:7.0.0
    init: confluentinc/confluent-init-container:2.2.0
    pullSecretRef:
      - confluent-registry
  dataVolumeCapacity: 10Gi
  tls:
    secretRef: origin-tls-group1
  listeners:
    internal:
      authentication:
        type: mtls
      tls:
        enabled: true
    external:
      authentication:
        type: mtls
      tls:
        enabled: true
  services:
    kafkaRest:
      authentication:
        type: basic
        basic:
          secretRef: credential
          roles:
            - Administrators
  ## dependencies are not required, will have default set
  dependencies:
    zookeeper:
      endpoint: zookeeper.origin.svc.cluster.local:2182
      authentication:
        type: mtls
      tls:
        enabled: true
---
apiVersion: platform.confluent.io/v1beta1
kind: KafkaTopic
metadata:
  name: demo
  namespace: origin
spec:
  replicas: 3
  partitionCount: 4
  configs:
    cleanup.policy: "delete"
  kafkaRestClassRef:
    name: origin-kafka-rest
---
apiVersion: platform.confluent.io/v1beta1
kind: KafkaRestClass
metadata:
  name: origin-kafka-rest
  namespace: origin
spec:
  kafkaClusterRef:
    name: kafka
  kafkaRest:
    endpoint: http://kafka.origin.svc.cluster.local:8090
    authentication:
      type: basic
      basic:
        secretRef: rest-credential
---
