apiVersion: platform.confluent.io/v1beta1
kind: ClusterLink
metadata:
  name: clusterlink-cflt
  namespace: destination
spec:
  destinationKafkaCluster:
    kafkaRestClassRef:
      name: destination-kafka-rest
      namespace: destination
  sourceKafkaCluster:
    bootstrapEndpoint: notcflt.destination.svc.cluster.local:9092
    clusterID: JhRCpEDwQ3mhH2ftOUvOcQ
  mirrorTopics:
  - name: demo
