apiVersion: v1
kind: Pod
metadata:
  name: notcflt
  labels:
    app.kubernetes.io/name: notcflt
spec:
  containers:
  - name: notcflt
    image: johnnypark/kafka-zookeeper
    ports:
      - containerPort: 9092
        name: listener
---
apiVersion: v1
kind: Service
metadata:
  name: notcflt
spec:
  selector:
    app.kubernetes.io/name: notcflt
  ports:
  - name: listener
    protocol: TCP
    port: 9092
    targetPort: 9092