apiVersion: core.cpc.platform.confluent.io/v1beta1
kind: KafkaClusterClass
metadata:
  name: kafka-standard
  namespace: cpc-system
  annotations:
    cpc.platform.confluent.io/description: "This TILE represents pre-set configuration to deploy CP Kafka Cluster."
spec:
  provisioner:
    type: cfk
    cfk:
      replicas: 3
      volume:
        data:
          capacity: 10Gi
